version: '3.8'

services:

  web:
    image: gianglh0469/clothes-shopping_web
    build: ./project/web
    command: "npm run start"
    volumes:
      - './project/web:/usr/src/app'
    ports:
      - 8080:8080
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=8080
    depends_on:
      - api

  api:
    image: gianglh0469/clothes-shopping_api
    build: ./project/api
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    volumes:
      - ./project/api:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/web_dev # new
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/web_test # new
    depends_on:
      # new
      - db

  # new
  db:
    image: gianglh0469/clothes-shopping_db
    build:
      context: ./project/db
      dockerfile: dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
