# Dockerfile
FROM node:lts-alpine

# create destination directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# update and install dependency
RUN apk update \
    && apk upgrade

# copy the app, note .dockerignore
COPY . .
RUN npm install
RUN npm run build